
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/alecwaumans/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.4.0 - x86_64
...
